<?php

declare(strict_types=1);

$reviews = [
    ['name' => 'Romuald BERNARD', 'date' => '2024-01-26', 'text' => 'Chouette expérience cette étude posturale. Accueil sympa. Conseils et réglages par un professionnel passionné. Bel échange, content de l\'avoir fait.'],
    ['name' => 'Vincent Padovan', 'date' => '2023-11-14', 'text' => 'Super moment auprès d’un professionnel qualifié pour analyser votre profil sur vélo, corriger votre position et l’optimiser. On se sent tout de suite en confiance de par sa sympathie, ses connaissances et son savoir-faire ! Je recommande !'],
    ['name' => 'Marc Fable', 'date' => '2023-11-13', 'text' => 'Séance de bike fitting pour analyser et surtout améliorer la position sur le vélo. N’hésitez pas, un vrai pro.'],
    ['name' => 'Thibaut Van Hauwe', 'date' => '2023-09-20', 'text' => 'Étude posturale au top ! À l’écoute des athlètes pour trouver le meilleur compromis entre aéro et confort. Très réactif pour les ajustements. Merci Adrien pour ton expertise !'],
    ['name' => 'Camille Borcy', 'date' => '2023-06-27', 'text' => 'Professionnalisme, expertise et accueil 5 étoiles.'],
    ['name' => 'caroline hallet', 'date' => '2023-06-26', 'text' => 'Service professionnel et de qualité. Adrien est toujours disponible en cas de question. Coaching adapté à nos objectifs. Je recommande à 100 %.'],
    ['name' => 'Aud “ADL” De L', 'date' => '2023-06-24', 'text' => 'Super coach ! Hyper sympa, très attentif aux éventuels bobos et aux capacités, même s’il motive à se surpasser ! Je recommande carrément.'],
    ['name' => 'Hugo Draguet', 'date' => '2023-06-23', 'text' => 'Supers conseils adaptés à nos besoins. Évaluations régulières avec le coach, qui s’adapte en fonction des objectifs, des ressentis et des données d’entraînement. Approche très professionnelle, tout en restant conviviale. Entraînements très bien détaillés, variés et adaptés.'],
    ['name' => 'Yann Le Cam', 'date' => '2023-06-23', 'text' => 'Pro-Fit et Adrien ont été mon coach sportif personnel pendant plusieurs années. Il a fait de moi un sportif régulier, ce que je n’étais pas. Il a travaillé le postural, la musculation, la souplesse, la détente antistress. Rigoureux, constant, créatif. Pro-Fit a aussi travaillé pour mon organisation (60 personnes en Europe) : un programme pour 10 collaborateurs, en entraînement personnalisé à distance. Je le recommande, en distanciel, ou mieux encore en présentiel.'],
    ['name' => 'seront Mehdi', 'date' => '2023-06-23', 'text' => 'Un suivi pro, personnalisé par rapport à mon objectif (être finisher d’un semi-marathon). Adrien a toujours été disponible pour répondre à mes questions. Je recommande à 100 %.'],
];

$links = [
    'book' => 'https://calendar.app.google/FJ2fs48nuAak519r5',
    'instagram' => 'https://www.instagram.com/adriengain_profitbe/',
    'facebook' => 'https://www.facebook.com/profile.php?id=100094413586785',
    'facebook_pro' => 'https://www.facebook.com/adriengainpro/',
    'linkedin' => 'https://www.linkedin.com/in/adrien-gain-95067b67/',
    'maps' => 'https://www.google.com/maps/search/?api=1&query=Rue+de+la+Bruy%C3%A8re+240+6001+Marcinelle',
    'google' => 'https://www.google.com/search?q=Pro-Fit.be+Marcinelle+avis',
    'bioracer' => 'https://bioracermotion.com/',
    'scicon' => 'https://sciconsports.com/fr-eu/collections/sac-transport-velo/products/housse-a-velo-triathlon-aerocomfort-3-0-tp033105013',
    'ldmedia' => 'https://ldmedia.be',
    'adrien_mail' => 'mailto:gain.adrien@gmail.com',
    'marion_mail' => 'mailto:marionvege@hotmail.com',
    'adrien_tel' => 'tel:+32474488273',
    'marion_tel' => 'tel:+32494108813',
];

$plans = [
    ['label' => '5 km', 'detail' => '4', 'price' => '40 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/5-km---4-semaines---niveau-debutant/'],
    ['label' => '10 km', 'detail' => '8', 'price' => '80 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/10-km---8-semaines---niveau-debutant---pro-fitbe/'],
    ['label' => 'Semi-marathon', 'detail' => '6', 'price' => '60 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/semi-marathon---6-semaines---niveau-intermediaire/'],
    ['label' => 'Marathon', 'detail' => '8', 'price' => '80 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/marathon---8-semaines---niveau-intermediaire/'],
    ['label' => 'Marathon', 'detail' => '12', 'price' => '120 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/marathon---12-semaines---niveau-intermediaire/'],
];

return [
    'fr' => [
        'meta' => [
            'home_title' => 'Pro-Fit Charleroi – Bike fitting, coaching sportif & kiné',
            'description' => 'Pro-Fit.be — préparation physique, kinésithérapie du sport et bike fitting, à Charleroi et à distance.',
        ],
        'nav' => [
            ['home', 'Accueil'],
            ['coaching', 'Coaching sportif'],
            ['velo', 'Bike fitting'],
            ['entreprise', 'Entreprise'],
            ['kinesitherapie', 'Kinésithérapie'],
            ['blog', 'Blog'],
            ['tarifs', 'Tarifs'],
            ['contact', 'Contact'],
        ],
        'book' => 'Réserver un bike fitting',
        'discover' => 'Découvrir',
        'hero' => [
            'kicker' => 'Charleroi · Marcinelle · à distance',
            'title' => 'Bike fitting, coaching sportif et kinésithérapie à Charleroi.',
            'lead' => 'Studio rue de la Bruyère 240 à Marcinelle. Adrien Gain y réalise des études posturales sur vélo et suit des sportifs en triathlon, cyclisme, running et trail. Marion Van Genechten consulte en kinésithérapie générale et sportive.',
        ],
        'services' => [
            ['coaching', 'Coaching sportif', 'Préparation physique', 'Studio à Charleroi et coaching à distance.', 'photo-coaching.jpg'],
            ['velo', 'Plan d’entraînement', 'Étude posturale sur vélo', 'Confort, puissance et aérodynamisme.', 'photo-bikefit.jpg'],
            ['entreprise', 'Coaching en entreprise', 'Santé et performance', 'Le bien-être des équipes au centre du rendement.', 'photo-entreprise.jpg'],
            ['kinesitherapie', 'Kinésithérapie', 'Générale et sportive', 'Réadaptation, au cabinet ou à domicile.', 'photo-kine.webp'],
        ],
        'pages' => [
            'coaching' => [
                'title' => 'Coaching sportif – Préparation physique',
                'kicker' => 'Studio à Marcinelle et suivi international',
                'image' => 'photo-coaching.jpg',
                'photos' => [
                    ['photo-coaching.jpg', 'Préparation physique'],
                    ['photo-coaching-trx.jpg', 'Personal training'],
                    ['photo-coaching-plank.jpg', 'Renforcement'],
                ],
                'paragraphs' => [
                    'Après avoir ciblé l’objet de votre demande (minceur, prise de masse, souplesse, recherche de force…) et réalisé une anamnèse globale sur base de vos données propres (fréquences cardiaques, masse graisseuse et masse maigre…), mon rôle en tant que coach sportif diplômé sera d’établir un programme personnalisé.',
                    'D’un point de vue pratique, le studio de coaching sportif situé à Charleroi (Marcinelle) est équipé avec tout le matériel nécessaire : rack de renforcement musculaire, kettlebells, Swiss ball, TRX, BOSU, anneaux.',
                    'Mon objectif est de vous offrir la possibilité de concrétiser le plus vite possible votre objectif. Et surtout de vous rendre apte à le refaire par vous-même dans le futur.',
                ],
                'list_title' => 'Les 3 grands avantages du personal training',
                'list' => [
                    'Le suivi personnalisé par votre coach sportif diplômé',
                    'Le suivi du poids et les conseils nutritionnels adaptés',
                    'La motivation et le soutien de votre coach à tout moment',
                ],
                'close' => 'Ne vous mettez plus de limites et commencez sans plus attendre en réservant votre première séance.',
            ],
            'velo' => [
                'title' => 'Plan d’entraînement et étude posturale sur vélo',
                'kicker' => 'Cyclisme, running, trail, triathlon',
                'image' => 'photo-bikefit.jpg',
                'photos' => [
                    ['photo-zwift.jpg', 'Entraînements sur votre plateforme favorite'],
                    ['photo-nolio.png', 'Nöliö, le suivi du plan d’entraînement'],
                    ['photo-analyse.jpg', 'Analyse vidéo du positionnement'],
                    ['photo-selle.jpg', 'Capteur de pression de selle Velometrik'],
                    ['photo-selles.webp', 'Essai de selles haut de gamme'],
                    ['photo-aero-ecran.jpg', 'Gains en puissance et en vitesse, en temps réel'],
                    ['photo-bikefit.jpg', 'Étude posturale dynamique sur vélo'],
                ],
                'paragraphs' => [
                    'Vous cherchez un plan d’entraînement en cyclisme, running, trail ou triathlon, avec un contact constant avec un entraîneur diplômé ?',
                    'Vous désirez optimiser votre positionnement sur votre vélo afin de trouver plus de confort, être plus performant et accroître votre aérodynamisme ?',
                    'Vous cherchez à être testé sur le terrain grâce à un appareil de mesure du lactate, et à vous entraîner selon des zones de travail déterminées ?',
                ],
                'list_title' => 'Sur place',
                'list' => [
                    'Entraînements applicables sur votre plateforme favorite, dont Nöliö',
                    'Analyse du cycle de pédalage et de la position aérodynamique',
                    'Capteur de pression de selle Velometrik et essai de selles haut de gamme',
                    'Simulation de soufflerie Bioracer Aero, en exclusivité en Wallonie',
                ],
                'blocks' => [
                    ['Plan d’entraînement', 'Un plan est envisageable en triathlon, cyclisme, running et trail. Une première entrevue détermine vos objectifs. Des tests à l’effort sur home-trainer, via le capteur Lactate Scout 4, analysent votre progression et précisent vos zones de travail.'],
                    ['Étude posturale dynamique', 'Analyse selon vos préférences motrices, votre pratique et vos attentes (aérodynamisme, puissance, confort). Après une anamnèse (tests posturaux et de mobilité) et une analyse du cycle de pédalage, les réglages sont appliqués sur votre vélo — route, triathlon, VTT — ainsi que les cales. Vous repartez avec un rapport avant / après. Un programme de renforcement et de stretching peut être proposé.'],
                ],
            ],
            'entreprise' => [
                'title' => 'Coaching en entreprise',
                'kicker' => 'La santé de l’entreprise, c’est aussi celle des équipes',
                'image' => 'photo-entreprise.jpg',
                'paragraphs' => [
                    'Chaque personne étant unique, l’intervention d’un personal trainer prend tout son sens dans l’amélioration des facultés physiques et psychologiques des employés.',
                    'De plus en plus de personnes s’éloignent des activités sportives et subissent leur sédentarité : horaires, vie de famille, manque de stimulations. Les conséquences touchent les défenses de l’organisme, les capacités physiques et l’épanouissement.',
                    'Certaines activités amènent les équipes à sortir de leur zone de confort, à se dépasser, et à développer combativité et coopération. Les bénéfices se retrouvent dans le bien-être, et aussi dans la productivité.',
                ],
                'list_title' => 'Bénéfices pour l’employeur',
                'list' => [
                    'Réduction de l’absentéisme et des accidents de travail',
                    'Amélioration des relations, de la qualité du travail et de l’engagement',
                    'Attractivité de l’entreprise et impact sur la culture',
                    'Meilleur moral, concentration, satisfaction, moins de stress',
                    'Réduction des coûts de santé et retour sur investissement',
                ],
                'blocks' => [
                    ['Comment cela se passe', 'Séance d’information et/ou questionnaire : besoins, attentes, nature des activités, mise en place concrète. Puis définition du programme, lancement du projet et suivi des résultats, avec ajustements.'],
                ],
            ],
            'kinesitherapie' => [
                'title' => 'Kinésithérapie générale et sportive',
                'kicker' => 'Marion Van Genechten · Marcinelle',
                'image' => 'photo-kine.webp',
                'paragraphs' => [
                    'Sur base de votre prescription médicale, un suivi de qualité est mis en place afin de répondre à vos attentes en réadaptation physique et fonctionnelle.',
                    'Au fil des consultations, le thérapeute propose un traitement adapté à la pathologie générale ou sportive, à l’écoute, en respectant votre rythme de progression.',
                    'Un suivi pluridisciplinaire peut être indiqué (ostéopathe, posturologue, podologue, préparateur physique), ainsi qu’un travail en autonomie, au cabinet ou à domicile.',
                ],
                'list_title' => 'Prise de rendez-vous',
                'list' => [
                    'Marion Van Genechten — +32 494 10 88 13',
                    'Rue de la Bruyère 240, 6001 Marcinelle',
                    'Déplacement à domicile possible (grand Charleroi)',
                ],
            ],
            'mentions' => [
                'title' => 'Mentions',
                'kicker' => 'Pro-Fit.be',
                'image' => 'logo.png',
                'paragraphs' => [
                    'Pro-Fit.be — Adrien Gain. TVA BE 0534.564.822.',
                    'Studio : rue de la Bruyère 240, 6001 Marcinelle (Charleroi).',
                    'Contact : gain.adrien@gmail.com · +32 474 48 82 73. Kinésithérapie : marionvege@hotmail.com · +32 494 10 88 13.',
                    'Ce site n’utilise qu’un cookie technique de session, le temps d’envoyer le formulaire de contact, et mémorise localement votre choix sur la bannière cookies. Les liens vers Google, Instagram, Facebook ou LinkedIn sont des sites externes.',
                ],
            ],
            'contact' => [
                'title' => 'Contact',
                'kicker' => 'Charleroi et à distance',
            ],
        ],
        'team' => [
            'title' => 'L’équipe',
            'people' => [
                [
                    'name' => 'Adrien Gain',
                    'role' => 'Coaching sportif – Préparation physique',
                    'place' => 'Studio à Charleroi et coaching à distance (international)',
                    'photo' => 'portrait-a.jpg',
                    'mail' => 'adrien_mail',
                    'tel' => 'adrien_tel',
                    'tel_label' => '+32 474 48 82 73',
                    'formations_title' => 'Formations en coaching sportif et bike fitting',
                    'formations' => [
                        'Bachelier en éducation physique (Henallux)',
                        'Diplôme universitaire européen en préparation physique (Université de Lille 2)',
                        'AUEC Réathlétisation du sportif (Université de Lille 2)',
                        'Bike Fitting – Préférences motrices 1.0 (Volodalen, Suisse)',
                        'Bike fitting – triathlon and time trial specifics (Gebiomized ISCO)',
                        'Nutrition du sportif (UCLouvain)',
                        'Posturologie et posturo-thérapie (SFER)',
                        'EXOS – Performance Specialist',
                        'Ironman® – Triathlon Certified Coach',
                        'Personal Training (Haute École Léonard de Vinci)',
                        'Taping sportif (UCLouvain)',
                        'Functional Movement Screening – FMS Level 1',
                        'La Clinique du Coureur 1.0',
                    ],
                ],
                [
                    'name' => 'Marion Van Genechten',
                    'role' => 'Kinésithérapie générale et sportive',
                    'place' => 'Studio situé à Charleroi',
                    'photo' => 'portrait-b.jpg',
                    'mail' => 'marion_mail',
                    'tel' => 'marion_tel',
                    'tel_label' => '+32 494 10 88 13',
                    'formations_title' => 'Formations en kinésithérapie',
                    'formations' => [
                        'Master en kinésithérapie (Condorcet, Tournai)',
                        'Kinésithérapie du sport (Kineac, Charleroi)',
                        'Gym Pilates appliquée à la kinésithérapie (SSK-Formation, Villeneuve d’Ascq)',
                        'AUEC Réathlétisation du sportif (Université de Lille 2)',
                    ],
                ],
            ],
        ],
        'reviews' => [
            'title' => 'Avis vérifiés',
            'lead' => 'Avis Google de personnes venues au studio.',
            'cta' => 'Lire les avis Google',
            'items' => $reviews,
        ],
        'instagram' => [
            'title' => 'Instagram',
            'handle' => '@adriengain_profitbe',
            'bio' => 'Préparation physique et plans d’entraînement. Étude posturale dynamique cyclisme. Nutrition du sportif.',
            'cta' => 'Suivre sur Instagram',
        ],
        'tarifs' => [
            'title' => 'Tarifs',
            'updated' => 'Mise à jour : 1er août 2025',
            'from' => 'À partir de',
            'month' => 'mois',
            'includes' => 'Inclus',
            'online' => [
                'Plan d’entraînement personnalisé en ligne',
                'Prise en compte de l’ensemble des objectifs',
                'Analyse des entraînements et suivi',
                'Contact constant via messagerie',
                'Ajustement quotidien du plan',
                'Conseils nutrition et équipement',
                'Accès gratuit à l’application Nöliö',
                'Paiement unique en début de suivi',
                '1 semaine de test gratuit et sans engagement',
                '−10 % sur les autres services',
            ],
            'offers' => [
                [
                    'name' => 'Triathlon – Cyclisme',
                    'from' => '60 €',
                    'rows' => [
                        ['12 mois', '720 €', '60 € / mois'],
                        ['6 mois', '420 €', '70 € / mois'],
                        ['3 mois', '240 €', '80 € / mois'],
                        ['1 mois', '90 €', ''],
                    ],
                ],
                [
                    'name' => 'Running – Trail',
                    'from' => '55 €',
                    'rows' => [
                        ['12 mois', '660 €', '55 € / mois'],
                        ['6 mois', '360 €', '60 € / mois'],
                        ['3 mois', '195 €', '65 € / mois'],
                        ['1 mois', '70 €', ''],
                    ],
                ],
            ],
            'fit' => [
                'title' => 'Étude posturale dynamique sur vélo',
                'from' => '200 €',
                'road' => 'Vélo de route, gravel ou VTT',
                'points' => [
                    'Ajustement analytique du positionnement',
                    'Capteur Velometrik (pression de selle)',
                    'Réglages de cales',
                    'Analyse vidéo du mouvement',
                    'Préférences motrices (terrien / aérien) et antécédents',
                    'Pré-fit et post-fit : posture, renforcement, stretching',
                ],
                'aero' => 'Vélo de chrono ou triathlon : Bioracer Aero, + 60 €. Le logiciel chiffre vos gains potentiels en puissance et en temps.',
                'second' => 'Option deuxième vélo : + 110 €.',
                'cleats' => 'Réglage des cales seul : 40 €.',
            ],
            'case' => [
                'title' => 'Location valise vélo',
                'from' => '30 €',
                'rows' => [
                    ['Jour', '30 €'],
                    ['Week-end', '70 €'],
                    ['Semaine', '120 €'],
                    ['Caution', '300 €'],
                ],
                'text' => 'L’Aerocomfort 3.0 Triathlon transporte un vélo de triathlon ou de chrono en avion, sans démonter la selle, la tige de selle, les pédales ni la majorité des guidons. Kit de protection compris (pédalier, prolongateurs, selle, dérailleur).',
            ],
            'ready' => [
                'title' => 'Plans préconçus',
                'lead' => 'Chaque plan prévoit un essai gratuit (première semaine offerte), l’application mobile et web, le suivi de la progression et les échanges avec l’entraîneur.',
                'weeks' => 'semaines',
            ],
        ],
        'blog' => [
            'title' => 'Le blog des sportifs',
            'lead' => 'Études posturales, entraînement et récits d’athlètes.',
            'read' => 'Lire',
            'back' => 'Retour au blog',
        ],
        'articles' => [
            [
                'slug' => 'etude-posturale-velo',
                'date' => '2023-09-06',
                'category' => 'Étude posturale',
                'title' => 'L’art et la science de l’étude posturale sur vélo',
                'excerpt' => 'Un bon ajustement aligne le vélo sur votre biomécanique : confort, efficacité, performance.',
                'image' => 'photo-selle.jpg',
                'body' => [
                    'Que vous soyez un cycliste occasionnel ou un cycliste sérieux, l’un des aspects les plus cruciaux de votre expérience à vélo est l’ajustement. Un bon ajustement personnalise le vélo pour la biomécanique de votre corps.',
                    'Pourquoi c’est important. L’ajustement ne se limite pas à la hauteur de selle ou à la position du guidon. Un vélo bien réglé limite l’inconfort, les douleurs articulaires et les blessures.',
                    'Confort : un vélo mal ajusté gâche la sortie, ou vous éloigne du vélo. Efficacité : un bon réglage optimise le transfert de puissance, coup de pédale après coup de pédale. Prévention : moins de contrainte inutile sur les articulations et les muscles. Performance : aérodynamisme, puissance, et de meilleures sorties longues ou en course.',
                    'Le processus. Un bike fitter qualifié commence par vos objectifs, votre expérience et votre santé, puis votre style, votre fréquence et le terrain. Des mesures (jambes, torse, bras) fondent les réglages. Le type et la taille de vélo peuvent être recommandés.',
                    'Hauteur et recul de selle pour une extension de jambe utile, sans surcharger le genou. Guidon réglé pour une portée et une position des mains confortables. Cales alignées si vous roulez en pédales automatiques. Évaluation dynamique : la position est observée en mouvement, puis affinée.',
                    'Ce n’est pas un réglage unique. Avec l’expérience, la forme, ou une douleur, l’ajustement se revoit. Un vélo bien réglé permet de rouler plus longtemps, plus vite, et avec plus de plaisir.',
                ],
            ],
            [
                'slug' => 'entrainement-polarise-80-20',
                'date' => '2025-01-28',
                'category' => 'Plan d’entraînement',
                'title' => 'L’entraînement polarisé : 80/20',
                'excerpt' => '80 % à basse intensité, 20 % à haute intensité : performer sans s’épuiser.',
                'image' => 'photo-polarise.jpg',
                'body' => [
                    'Le principe 80/20 vise à optimiser les performances tout en limitant le surentraînement et la fatigue. L’intensité se répartit en deux zones : basse et haute.',
                    '80 % de l’entraînement se fait à intensité faible à modérée, pour l’endurance et l’aérobie : course, vélo ou natation à un rythme où l’on peut parler. 20 % se fait à intensité élevée : intervalles, sprints, efforts qui poussent le corps.',
                    'L’objectif est de progresser sans fatigue excessive ni blessure. Le corps récupère mieux et s’adapte. Pour l’endurance, cette base aérobie est essentielle sur la durée.',
                    'La méthode invite à écouter le corps. Les jours bas, mieux vaut rester à faible intensité. Sur 10 heures par semaine, 8 heures restent faciles et 2 heures sont intenses.',
                    'Équilibrer faible et haute intensité maximise les bénéfices et garde une pratique durable. Mise à jour : 28 janvier 2025.',
                ],
            ],
            [
                'slug' => 'meditation-et-sport',
                'date' => '2023-09-11',
                'category' => 'Préparation physique',
                'title' => 'Les bienfaits de la méditation pour la santé mentale et le bien-être physique',
                'excerpt' => 'Moins de stress, plus de concentration, un meilleur sommeil, un système immunitaire plus solide.',
                'image' => 'meditation.jpg',
                'body' => [
                    'La méditation est une pratique ancienne qui gagne en popularité.',
                    'En l’intégrant au quotidien, on peut réduire le stress, améliorer la concentration, renforcer la résilience émotionnelle, améliorer le sommeil et soutenir le système immunitaire.',
                ],
            ],
            [
                'slug' => 'kona-marjolaine',
                'date' => '2026-02-15',
                'category' => 'Compte rendu d’athlète',
                'title' => 'Championnats du monde Ironman à Hawaï pour Marjolaine',
                'excerpt' => 'Deux semaines après Kona : une qualification inattendue, et une journée à honorer.',
                'image' => 'photo-marjo.jpg',
                'body' => [
                    'Deux semaines se sont écoulées depuis le Championnat du Monde Ironman à Kona. Assez pour que l’adrénaline retombe. Le corps a récupéré, le quotidien a repris. Et c’est dans cette normalité que je mesure vraiment ce que j’ai vécu.',
                    'Je ne m’attendais pas à être qualifiée pour Kona. Trois mois pour préparer un championnat du monde, entre le travail, la logistique du voyage et un apprentissage express du vélo contre-la-montre. C’était intense, parfois trop.',
                    'Puis on arrive sur cette île. Le travail est fait, on profite de chaque jour, de cette fête autour du sport. Le jour J, une excitation sereine. Impossible de s’aligner sans un peu de doute, mais avec le sentiment d’être prête.',
                    'Une natation longue, houleuse, mais belle. L’eau était claire, pleine de poissons. J’ai nagé sans pression, juste avec la joie d’être là.',
                    'Un vélo plus difficile que prévu. La chaleur, le vent, la position aéro encore nouvelle. Des douleurs, quelques doutes, puis j’ai accepté de ralentir. J’ai pensé au marathon, à la suite, à l’essentiel.',
                    'Une course à pied d’abord douloureuse. Puis, comme souvent, tout s’est débloqué. Le corps a trouvé son rythme, le mental s’est apaisé. Glaçons, bob, sourires. J’ai avancé le cœur léger. Quand j’ai franchi la ligne, j’étais simplement bien. Présente. Reconnaissante.',
                    'Deuxième Ironman. Mais sûrement pas le dernier. — Marjolaine',
                ],
            ],
        ],
        'contact' => [
            'title' => 'Écrire au studio',
            'lead' => 'Une question sur un plan, un bike fitting ou la kinésithérapie. Nous répondons directement.',
            'name' => 'Nom',
            'email' => 'E-mail',
            'phone' => 'Téléphone',
            'message' => 'Message',
            'subject' => 'Sujet',
            'subjects' => [
                'coaching' => 'Coaching sportif',
                'bikefit' => 'Bike fitting',
                'plan' => 'Plan d’entraînement',
                'entreprise' => 'Coaching en entreprise',
                'kine' => 'Kinésithérapie',
                'autre' => 'Autre demande',
            ],
            'reply' => 'Vous préférez être recontacté',
            'reply_email' => 'Par e-mail',
            'reply_phone' => 'Par téléphone',
            'send' => 'Envoyer',
            'success' => 'Message bien reçu. Nous vous répondons rapidement.',
            'error' => 'Merci de vérifier le nom, l’e-mail et le message.',
            'address' => 'Rue de la Bruyère 240, 6001 Marcinelle',
        ],
        'footer' => 'TVA BE 0534.564.822',
        'cookies' => 'Aucun traceur n’est chargé tant que vous n’avez pas accepté. Le choix est mémorisé 6 mois sur cet appareil.',
        'cookies_ok' => 'Accepter',
        'cookies_no' => 'Refuser',
        'cookies_manage' => 'Gérer les cookies',
        'map' => 'Voir sur Google Maps',
        'links' => $links,
        'plans' => $plans,
    ],
    'en' => [
        'meta' => [
            'home_title' => 'Sports coaching, physiotherapy and bike fitting in Charleroi',
            'description' => 'Pro-Fit.be — physical preparation, sports physiotherapy and bike fitting, in Charleroi and remotely.',
        ],
        'nav' => [
            ['home', 'Home'],
            ['coaching', 'Sports coaching'],
            ['velo', 'Bike fitting'],
            ['entreprise', 'Corporate'],
            ['kinesitherapie', 'Physiotherapy'],
            ['blog', 'Blog'],
            ['tarifs', 'Prices'],
            ['contact', 'Contact'],
        ],
        'book' => 'Book a bike fit',
        'discover' => 'Discover',
        'hero' => [
            'kicker' => 'Charleroi · Marcinelle · remote',
            'title' => 'Bike fitting, sports coaching and physiotherapy in Charleroi.',
            'lead' => 'A studio at 240 rue de la Bruyère in Marcinelle. Adrien Gain runs bike fits and coaches triathlon, cycling, running and trail. Marion Van Genechten sees patients for general and sports physiotherapy.',
        ],
        'services' => [
            ['coaching', 'Sports coaching', 'Physical preparation', 'Studio in Charleroi and remote coaching.', 'photo-coaching.jpg'],
            ['velo', 'Training plan', 'Dynamic bike fit', 'Comfort, power and aerodynamics.', 'photo-bikefit.jpg'],
            ['entreprise', 'Corporate coaching', 'Health and performance', 'Employee wellbeing at the centre of performance.', 'photo-entreprise.jpg'],
            ['kinesitherapie', 'Physiotherapy', 'General and sports', 'Rehab at the studio or at home.', 'photo-kine.webp'],
        ],
        'pages' => [
            'coaching' => [
                'title' => 'Sports coaching – Physical preparation',
                'kicker' => 'Studio in Marcinelle and international follow-up',
                'image' => 'photo-coaching.jpg',
                'photos' => [
                    ['photo-coaching.jpg', 'Physical preparation'],
                    ['photo-coaching-trx.jpg', 'Personal training'],
                    ['photo-coaching-plank.jpg', 'Strength work'],
                ],
                'paragraphs' => [
                    'Once your goal is clear (fat loss, muscle gain, mobility, strength…) and a full assessment is done from your own data (heart rate, fat mass, lean mass…), my role as a qualified coach is to build a personal programme.',
                    'The coaching studio in Charleroi (Marcinelle) has the equipment you need: a strength rack, kettlebells, Swiss ball, TRX, BOSU and rings.',
                    'My aim is to help you reach your goal as soon as it is realistic — and to leave you able to do it again on your own.',
                ],
                'list_title' => 'Three advantages of personal training',
                'list' => [
                    'Follow-up by a qualified coach',
                    'Weight tracking and adapted nutrition advice',
                    'Motivation and support whenever you need it',
                ],
                'close' => 'Stop setting limits. Book a first session.',
            ],
            'velo' => [
                'title' => 'Training plans and dynamic bike fitting',
                'kicker' => 'Cycling, running, trail, triathlon',
                'image' => 'photo-bikefit.jpg',
                'photos' => [
                    ['photo-zwift.jpg', 'Training on the platform you already use'],
                    ['photo-nolio.png', 'Nöliö, follow-up for the training plan'],
                    ['photo-analyse.jpg', 'Video analysis of the position'],
                    ['photo-selle.jpg', 'Velometrik saddle pressure sensor'],
                    ['photo-selles.webp', 'Try a range of high-end saddles'],
                    ['photo-aero-ecran.jpg', 'Power and speed gains, in real time'],
                    ['photo-bikefit.jpg', 'Dynamic bike fitting'],
                ],
                'paragraphs' => [
                    'Looking for a cycling, running, trail or triathlon plan, with regular contact with a qualified coach?',
                    'Want a better position on the bike: more comfort, more performance, more aerodynamics?',
                    'Want field testing with a lactate meter, then training zones you can actually use?',
                ],
                'list_title' => 'In the studio',
                'list' => [
                    'Sessions you can load on your usual platform, including Nöliö',
                    'Pedal-stroke and aerodynamic position analysis',
                    'Velometrik saddle-pressure sensor and a range of high-end saddles',
                    'Bioracer Aero wind-tunnel simulation, exclusive in Wallonia',
                ],
                'blocks' => [
                    ['Training plan', 'Plans are available for triathlon, cycling, running and trail. A first meeting sets the goals. Effort tests on a home trainer, with the Lactate Scout 4 sensor, track progress and define training zones.'],
                    ['Dynamic bike fit', 'The fit follows your motor preferences, your discipline and what you want (aero, power, comfort). After posture and mobility tests and a pedal-stroke analysis, adjustments are made on your bike — road, triathlon, MTB — including cleats. You leave with a before / after report. A strength and stretching programme can be added.'],
                ],
            ],
            'entreprise' => [
                'title' => 'Corporate coaching',
                'kicker' => 'A healthier company starts with healthier people',
                'image' => 'photo-entreprise.jpg',
                'paragraphs' => [
                    'Because every person is different, a personal trainer can improve both the physical and psychological capacities of employees.',
                    'Many people drop sport and live with the consequences of sitting still: schedules, family life, lack of a spark. That shows up in immunity, physical capacity and how people feel at work.',
                    'The right activities take teams out of their usual comfort zone, and build both drive and cooperation. The gain is wellbeing, and also productivity.',
                ],
                'list_title' => 'What the employer gets',
                'list' => [
                    'Less absenteeism and fewer workplace accidents',
                    'Better relationships, work quality and engagement',
                    'A more attractive company and a stronger culture',
                    'Better morale, focus and job satisfaction, less stress',
                    'Lower health costs and a real return',
                ],
                'blocks' => [
                    ['How it works', 'An information session and/or a questionnaire: needs, expectations, which activities, and how they fit the company. Then the programme is defined, launched and adjusted from the results.'],
                ],
            ],
            'kinesitherapie' => [
                'title' => 'General and sports physiotherapy',
                'kicker' => 'Marion Van Genechten · Marcinelle',
                'image' => 'photo-kine.webp',
                'paragraphs' => [
                    'With your medical prescription, care is set up around what you need in physical and functional rehab.',
                    'Session after session, treatment matches a general or sports condition, at your pace.',
                    'A multidisciplinary path can be suggested (osteopath, posturologist, podiatrist, strength coach), plus work you do on your own at the studio or at home.',
                ],
                'list_title' => 'Book an appointment',
                'list' => [
                    'Marion Van Genechten — +32 494 10 88 13',
                    'Rue de la Bruyère 240, 6001 Marcinelle',
                    'Home visits possible across greater Charleroi',
                ],
            ],
            'mentions' => [
                'title' => 'Legal',
                'kicker' => 'Pro-Fit.be',
                'image' => 'logo.png',
                'paragraphs' => [
                    'Pro-Fit.be — Adrien Gain. VAT BE 0534.564.822.',
                    'Studio: rue de la Bruyère 240, 6001 Marcinelle (Charleroi), Belgium.',
                    'Contact: gain.adrien@gmail.com · +32 474 48 82 73. Physiotherapy: marionvege@hotmail.com · +32 494 10 88 13.',
                    'This site only uses a technical session cookie while the contact form is sent, and stores your cookie choice locally in the browser. Google, Instagram, Facebook and LinkedIn links are external sites.',
                ],
            ],
            'contact' => [
                'title' => 'Contact',
                'kicker' => 'Charleroi and remote',
            ],
        ],
        'team' => [
            'title' => 'The team',
            'people' => [
                [
                    'name' => 'Adrien Gain',
                    'role' => 'Sports coaching – Physical preparation',
                    'place' => 'Studio in Charleroi and remote coaching (international)',
                    'photo' => 'portrait-a.jpg',
                    'mail' => 'adrien_mail',
                    'tel' => 'adrien_tel',
                    'tel_label' => '+32 474 48 82 73',
                    'formations_title' => 'Coaching and bike-fitting training',
                    'formations' => [
                        'Bachelor in physical education (Henallux)',
                        'European university diploma in physical preparation (University of Lille 2)',
                        'AUEC athlete reconditioning (University of Lille 2)',
                        'Bike Fitting – Motor preferences 1.0 (Volodalen, Switzerland)',
                        'Bike fitting – triathlon and time trial specifics (Gebiomized ISCO)',
                        'Sports nutrition (UCLouvain)',
                        'Posturology and posturo-therapy (SFER)',
                        'EXOS – Performance Specialist',
                        'Ironman® – Triathlon Certified Coach',
                        'Personal Training (Haute École Léonard de Vinci)',
                        'Sports taping (UCLouvain)',
                        'Functional Movement Screening – FMS Level 1',
                        'La Clinique du Coureur 1.0',
                    ],
                ],
                [
                    'name' => 'Marion Van Genechten',
                    'role' => 'General and sports physiotherapy',
                    'place' => 'Studio in Charleroi',
                    'photo' => 'portrait-b.jpg',
                    'mail' => 'marion_mail',
                    'tel' => 'marion_tel',
                    'tel_label' => '+32 494 10 88 13',
                    'formations_title' => 'Physiotherapy training',
                    'formations' => [
                        'Master in physiotherapy (Condorcet, Tournai)',
                        'Sports physiotherapy (Kineac, Charleroi)',
                        'Pilates applied to physiotherapy (SSK-Formation, Villeneuve d’Ascq)',
                        'AUEC athlete reconditioning (University of Lille 2)',
                    ],
                ],
            ],
        ],
        'reviews' => [
            'title' => 'Verified reviews',
            'lead' => 'Google reviews from people who came to the studio.',
            'cta' => 'Read the Google reviews',
            'items' => $reviews,
        ],
        'instagram' => [
            'title' => 'Instagram',
            'handle' => '@adriengain_profitbe',
            'bio' => 'Physical preparation and training plans. Dynamic cycling bike fits. Sports nutrition.',
            'cta' => 'Follow on Instagram',
        ],
        'tarifs' => [
            'title' => 'Prices',
            'updated' => 'Updated 1 August 2025',
            'from' => 'From',
            'month' => 'month',
            'includes' => 'Included',
            'online' => [
                'Personal online training plan',
                'Every goal is taken into account',
                'Session analysis and follow-up',
                'Constant contact by message',
                'Daily plan adjustments',
                'Nutrition and equipment advice',
                'Free access to the Nöliö app',
                'Single payment at the start',
                'One free trial week, no commitment',
                '−10% on other services',
            ],
            'offers' => [
                [
                    'name' => 'Triathlon – Cycling',
                    'from' => '€60',
                    'rows' => [
                        ['12 months', '€720', '€60 / month'],
                        ['6 months', '€420', '€70 / month'],
                        ['3 months', '€240', '€80 / month'],
                        ['1 month', '€90', ''],
                    ],
                ],
                [
                    'name' => 'Running – Trail',
                    'from' => '€55',
                    'rows' => [
                        ['12 months', '€660', '€55 / month'],
                        ['6 months', '€360', '€60 / month'],
                        ['3 months', '€195', '€65 / month'],
                        ['1 month', '€70', ''],
                    ],
                ],
            ],
            'fit' => [
                'title' => 'Dynamic bike fit',
                'from' => '€200',
                'road' => 'Road, gravel or MTB',
                'points' => [
                    'Analytical position adjustment',
                    'Velometrik saddle-pressure sensor',
                    'Cleat setup',
                    'Video movement analysis',
                    'Motor preferences (terrestrial / aerial) and medical history',
                    'Pre-fit and post-fit: posture, strength, stretching',
                ],
                'aero' => 'Time-trial or triathlon bike: Bioracer Aero, + €60. The software estimates potential gains in power and time.',
                'second' => 'Second bike option: + €110.',
                'cleats' => 'Cleat adjustment only: €40.',
            ],
            'case' => [
                'title' => 'Bike travel-case hire',
                'from' => '€30',
                'rows' => [
                    ['Day', '€30'],
                    ['Weekend', '€70'],
                    ['Week', '€120'],
                    ['Deposit', '€300'],
                ],
                'text' => 'The Aerocomfort 3.0 Triathlon flies a triathlon or time-trial bike without removing the saddle, seatpost, pedals or most handlebars. Protection kit included (crank, extensions, saddle, derailleur).',
            ],
            'ready' => [
                'title' => 'Ready-made plans',
                'lead' => 'Each plan includes a free trial (first week on the coach), the mobile and web app, progress tracking and messages with the coach.',
                'weeks' => 'weeks',
            ],
        ],
        'blog' => [
            'title' => 'The athletes’ blog',
            'lead' => 'Bike fits, training and athlete stories.',
            'read' => 'Read',
            'back' => 'Back to the blog',
        ],
        'articles' => [
            [
                'slug' => 'etude-posturale-velo',
                'date' => '2023-09-06',
                'category' => 'Bike fit',
                'title' => 'The art and science of a dynamic bike fit',
                'excerpt' => 'A proper fit matches the bike to your body: comfort, efficiency, performance.',
                'image' => 'photo-selle.jpg',
                'body' => [
                    'Whether you ride occasionally or seriously, fit is one of the most important parts of cycling. A good fit tunes the bike to your biomechanics.',
                    'Why it matters. Fit is more than saddle height or handlebar position. A well-set bike reduces discomfort, joint pain and injury.',
                    'Comfort: a poor fit spoils the ride, or stops you riding. Efficiency: a good setup transfers power, pedal stroke after pedal stroke. Injury prevention: less useless load on joints and muscles. Performance: aerodynamics, power, and better long rides or races.',
                    'The process. A qualified fitter starts with your goals, experience and health, then your style, frequency and terrain. Body measurements (legs, torso, arms) drive the adjustments. Bike type and size can be recommended.',
                    'Saddle height and setback for a useful leg extension, without overloading the knee. Handlebar reach and hand position that spare the back, shoulders and arms. Cleats aligned if you ride clipless. A dynamic check: position is watched while you pedal, then refined.',
                    'It is not a one-off. Experience, fitness, or pain are reasons to revisit the fit. A well-set bike lets you ride longer, faster, and with more pleasure.',
                ],
            ],
            [
                'slug' => 'entrainement-polarise-80-20',
                'date' => '2025-01-28',
                'category' => 'Training plan',
                'title' => 'Polarised training: 80/20',
                'excerpt' => '80% easy, 20% hard: get faster without burning out.',
                'image' => 'photo-polarise.jpg',
                'body' => [
                    'The 80/20 principle aims to raise performance while limiting overtraining and fatigue. Intensity sits in two zones: low and high.',
                    '80% of training is easy to moderate, building endurance and aerobic capacity: running, cycling or swimming at a conversational pace. 20% is hard: intervals, sprints, efforts that push the body.',
                    'The goal is progress without excess fatigue or injury. The body recovers and adapts. For endurance athletes, that aerobic base is what lasts.',
                    'The method asks you to listen. On low days, stay easy. In a 10-hour week, 8 hours stay easy and 2 hours are intense.',
                    'Balancing easy and hard work keeps the gains and the habit. Updated 28 January 2025.',
                ],
            ],
            [
                'slug' => 'meditation-et-sport',
                'date' => '2023-09-11',
                'category' => 'Physical preparation',
                'title' => 'How meditation supports mental health and physical wellbeing',
                'excerpt' => 'Less stress, sharper focus, better sleep, a stronger immune system.',
                'image' => 'meditation.jpg',
                'body' => [
                    'Meditation is an old practice that is finding a new audience.',
                    'Brought into daily life, it can reduce stress, improve concentration, strengthen emotional resilience, improve sleep and support the immune system.',
                ],
            ],
            [
                'slug' => 'kona-marjolaine',
                'date' => '2026-02-15',
                'category' => 'Athlete report',
                'title' => 'Ironman World Championship in Hawaii for Marjolaine',
                'excerpt' => 'Two weeks after Kona: an unexpected qualification, and a day worth honouring.',
                'image' => 'photo-marjo.jpg',
                'body' => [
                    'Two weeks have passed since the Ironman World Championship in Kona. Long enough for the adrenaline to drop. The body has recovered, ordinary life is back. In that ordinary quiet, I can finally measure what I lived.',
                    'I did not expect to qualify for Kona. Three months to prepare a world championship, between work, travel logistics and a crash course on the time-trial bike. It was intense. Sometimes too much.',
                    'Then you land on the island. The work is done. You take each day, and the festival around the sport. On race morning, a calm excitement. You cannot start a day like that without some doubt — and still feel ready.',
                    'A long, choppy, beautiful swim. The water was clear, full of fish. I swam without pressure, just glad to be there.',
                    'The bike was harder than expected. Heat, wind, an aero position that was still new. Pain, a few doubts, then I accepted slowing down. I thought about the marathon, about what came next, about what mattered.',
                    'The run hurt at first. Then, as it often does, it opened up. The body found a rhythm, the mind settled. Ice, a cap, smiles. I moved forward lightly. Crossing the line, I simply felt well. Present. Grateful.',
                    'Second Ironman. Certainly not the last. — Marjolaine',
                ],
            ],
        ],
        'contact' => [
            'title' => 'Write to the studio',
            'lead' => 'A question about a plan, a bike fit or physiotherapy. We reply directly.',
            'name' => 'Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'message' => 'Message',
            'subject' => 'Subject',
            'subjects' => [
                'coaching' => 'Sports coaching',
                'bikefit' => 'Bike fitting',
                'plan' => 'Training plan',
                'entreprise' => 'Corporate coaching',
                'kine' => 'Physiotherapy',
                'autre' => 'Something else',
            ],
            'reply' => 'How should we reply',
            'reply_email' => 'By email',
            'reply_phone' => 'By phone',
            'send' => 'Send',
            'success' => 'Message received. We will reply shortly.',
            'error' => 'Please check the name, email and message.',
            'address' => 'Rue de la Bruyère 240, 6001 Marcinelle',
        ],
        'footer' => 'VAT BE 0534.564.822',
        'cookies' => 'No tracker is loaded until you accept. The choice is stored for 6 months on this device.',
        'cookies_ok' => 'Accept',
        'cookies_no' => 'Refuse',
        'cookies_manage' => 'Manage cookies',
        'map' => 'Open in Google Maps',
        'links' => $links,
        'plans' => $plans,
    ],
];
