<?php

declare(strict_types=1);

$reviews = [
    ['name' => 'Romuald BERNARD', 'date' => '2024-01-26', 'text' => 'Chouette expérience cette étude posturale. Accueil sympa. Conseils et réglages par un professionnel passionné. Bel échange, content de l\'avoir fait.'],
    ['name' => 'Vincent Padovan', 'date' => '2023-11-14', 'text' => 'Super moment auprès d’un professionnel qualifié pour analyser votre profil sur vélo, corriger votre position et l’optimiser. On se sent tout de suite en confiance de par sa sympathie, ses connaissances et son savoir-faire ! Je recommande !'],
    ['name' => 'Marc Fable', 'date' => '2023-11-13', 'text' => 'Séance de bike fitting pour analyser et surtout améliorer la position sur le vélo. N’hésitez pas, un vrai pro.'],
    ['name' => 'Thibaut Van Hauwe', 'date' => '2023-09-20', 'text' => 'Étude posturale au top ! À l’écoute des athlètes pour trouver le meilleur compromis entre aéro et confort. Très réactif pour les ajustements. Merci Adrien pour ton expertise !'],
    ['name' => 'Camille Borcy', 'date' => '2023-06-27', 'text' => 'Professionnalisme, expertise et accueil 5 étoiles.'],
    ['name' => 'caroline hallet', 'date' => '2023-06-26', 'text' => 'Service professionnel et de qualité. Adrien est toujours disponible en cas de question. Coaching adapté à nos objectifs. Je recommande à 100 %.'],
    ['name' => 'Aud “ADL” De L', 'date' => '2023-06-24', 'text' => 'Super coach ! Hyper sympa, très attentif aux éventuels bobos et aux capacités, même s’il motive à se surpasser ! Je recommande carrément.'],
    ['name' => 'Hugo Draguet', 'date' => '2023-06-23', 'text' => 'Supers conseils adaptés à nos besoins. Évaluations régulières avec le coach, qui s’adapte en fonction des objectifs, des ressentis et des données d’entraînement. Approche très professionnelle, tout en restant conviviale. Entraînements très bien détaillés, variés et adaptés.'],
    ['name' => 'Yann Le Cam', 'date' => '2023-06-23', 'text' => 'Pro-Fit et Adrien ont été mon coach sportif personnel pendant plusieurs années. Il a fait de moi un sportif régulier, ce que je n’étais pas. Il a travaillé le postural, la musculation, la souplesse, la détente antistress. Rigoureux, constant, créatif. Pro-Fit a aussi travaillé pour mon organisation (60 personnes en Europe) : un programme pour 10 collaborateurs, en entraînement personnalisé à distance. Je le recommande, en distanciel, ou mieux encore en présentiel.'],
    ['name' => 'seront Mehdi', 'date' => '2023-06-23', 'text' => 'Un suivi pro, personnalisé par rapport à mon objectif (être finisher d’un semi-marathon). Adrien a toujours été disponible pour répondre à mes questions. Je recommande à 100 %.'],
];

$links = [
    'book' => 'https://calendar.app.google/FJ2fs48nuAak519r5',
    'instagram' => 'https://www.instagram.com/adriengain_profitbe/',
    'facebook' => 'https://www.facebook.com/profile.php?id=61553046915417',
    'facebook_pro' => 'https://www.facebook.com/adriengainpro/',
    'linkedin' => 'https://www.linkedin.com/in/adrien-gain-95067b67/',
    'maps' => 'https://www.google.com/maps/search/?api=1&query=Rue+de+la+Bruy%C3%A8re+240+6001+Marcinelle',
    'google' => 'https://www.google.com/search?q=Pro-Fit.be+Marcinelle+avis',
    'bioracer' => 'https://bioracermotion.com/',
    'scicon' => 'https://sciconsports.com/fr-eu/collections/sac-transport-velo/products/housse-a-velo-triathlon-aerocomfort-3-0-tp033105013',
    'ldmedia' => 'https://ldmedia.be',
    'adrien_mail' => 'mailto:gain.adrien@gmail.com',
    'marion_mail' => 'mailto:marionvege@hotmail.com',
    'adrien_tel' => 'tel:+32474488273',
    'marion_tel' => 'tel:+32494108813',
];

$plans = [
    ['label' => '5 km', 'detail' => '4', 'price' => '40 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/5-km---4-semaines---niveau-debutant/'],
    ['label' => '10 km', 'detail' => '8', 'price' => '80 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/10-km---8-semaines---niveau-debutant---pro-fitbe/'],
    ['label' => 'Semi-marathon', 'detail' => '6', 'price' => '60 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/semi-marathon---6-semaines---niveau-intermediaire/'],
    ['label' => 'Marathon', 'detail' => '8', 'price' => '80 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/marathon---8-semaines---niveau-intermediaire/'],
    ['label' => 'Marathon', 'detail' => '12', 'price' => '120 €', 'href' => 'https://www.nolio.io/coach/adrien.gain.76831/training-plan/marathon---12-semaines---niveau-intermediaire/'],
];

return [
    'fr' => [
        'meta' => [
            'home_title' => 'Pro-Fit Charleroi – Bike fitting, plans d’entraînement & kiné',
            'description' => 'Pro-Fit.be — plans d’entraînement, kinésithérapie du sport et bike fitting, à Charleroi et à distance.',
        ],
        'nav' => [
            ['home', 'Accueil'],
            ['velo', 'Plan d’entraînement'],
            ['kinesitherapie', 'Kinésithérapie'],
            ['blog', 'Blog'],
            ['tarifs', 'Tarifs'],
            ['contact', 'Contact'],
        ],
        'book' => 'Réserver un bike fitting',
        'discover' => 'Découvrir',
        'hero' => [
            'kicker' => 'Charleroi · Marcinelle · à distance',
            'title' => 'Bike fitting, plans d’entraînement et kinésithérapie à Charleroi.',
            'lead' => 'Studio rue de la Bruyère 240 à Marcinelle. Adrien Gain y réalise des études posturales sur vélo et suit des sportifs en triathlon, cyclisme, running et trail. Marion Van Genechten consulte en kinésithérapie générale et sportive.',
        ],
        'services' => [
            ['velo', 'Plan d’entraînement', 'Étude posturale sur vélo', 'Confort, puissance et aérodynamisme.', 'photo-bikefit.jpg'],
            ['kinesitherapie', 'Kinésithérapie', 'Générale et sportive', 'Réadaptation, au cabinet ou à domicile.', 'photo-kine.webp'],
        ],
        'pages' => [
            'coaching' => [
                'title' => 'Coaching sportif – Préparation physique',
                'kicker' => 'Studio à Marcinelle et suivi international',
                'image' => 'photo-coaching.jpg',
                'photos' => [
                    ['photo-coaching.jpg', 'Préparation physique'],
                    ['photo-coaching-trx.jpg', 'Personal training'],
                    ['photo-coaching-plank.jpg', 'Renforcement'],
                ],
                'paragraphs' => [
                    'Après avoir ciblé l’objet de votre demande (minceur, prise de masse, souplesse, recherche de force…) et réalisé une anamnèse globale sur base de vos données propres (fréquences cardiaques, masse graisseuse et masse maigre…), mon rôle en tant que coach sportif diplômé sera d’établir un programme personnalisé.',
                    'D’un point de vue pratique, le studio de coaching sportif situé à Charleroi (Marcinelle) est équipé avec tout le matériel nécessaire : rack de renforcement musculaire, kettlebells, Swiss ball, TRX, BOSU, anneaux.',
                    'Mon objectif est de vous offrir la possibilité de concrétiser le plus vite possible votre objectif. Et surtout de vous rendre apte à le refaire par vous-même dans le futur.',
                ],
                'list_title' => 'Les 3 grands avantages du personal training',
                'list' => [
                    'Le suivi personnalisé par votre coach sportif diplômé',
                    'Le suivi du poids et les conseils nutritionnels adaptés',
                    'La motivation et le soutien de votre coach à tout moment',
                ],
                'close' => 'Ne vous mettez plus de limites et commencez sans plus attendre en réservant votre première séance.',
            ],
            'velo' => [
                'title' => 'Plan d’entraînement et étude posturale sur vélo',
                'kicker' => 'Cyclisme, running, trail, triathlon',
                'image' => 'photo-bikefit.jpg',
                'paragraphs' => [
                    'Vous cherchez un plan d’entraînement en cyclisme, running, trail ou triathlon, avec un contact constant avec un entraîneur diplômé ?',
                    'Vous désirez optimiser votre positionnement sur votre vélo afin de trouver plus de confort, être plus performant et accroître votre aérodynamisme ?',
                    'Vous cherchez à être testé sur le terrain grâce à un appareil de mesure du lactate, et à vous entraîner selon des zones de travail déterminées ?',
                    'Votre niveau sportif requiert un travail supplémentaire en dehors des entraînements propres à votre discipline, collective ou individuelle ?',
                ],
                'sections' => [
                    [
                        'title' => 'Plan d’entraînement',
                        'paragraphs' => [
                            'Un plan est envisageable en triathlon, cyclisme, running et trail. Une première entrevue détermine vos objectifs. Des tests à l’effort sur home-trainer, via le capteur Lactate Scout 4, analysent votre progression et précisent vos zones de travail.',
                        ],
                        'photos' => [
                            ['photo-zwift.jpg', 'Entraînements sur votre plateforme favorite'],
                            ['photo-nolio.png', 'Nöliö, le suivi du plan d’entraînement'],
                        ],
                    ],
                    [
                        'title' => 'Étude posturale dynamique',
                        'paragraphs' => [
                            'Analyse selon vos préférences motrices, votre pratique et vos attentes (aérodynamisme, puissance, confort). Après une anamnèse (tests posturaux et de mobilité) et une analyse du cycle de pédalage, les réglages sont appliqués sur votre vélo — route, triathlon, VTT — ainsi que les cales.',
                            'Le capteur de pression de selle Velometrik sert à vous placer correctement. Un kit de selles haut de gamme est à disposition pendant l’étude. Pour les athlètes plus compétitifs, et en exclusivité en Wallonie, la simulation de soufflerie Bioracer Aero chiffre vos gains en puissance et en vitesse, en temps réel.',
                            'Vous repartez avec un rapport avant / après, et un programme de renforcement et de stretching peut être proposé.',
                        ],
                        'photos' => [
                            ['photo-analyse.jpg', 'Analyse vidéo du positionnement'],
                            ['photo-aero-ecran.jpg', 'Gains en puissance et en vitesse, en temps réel'],
                            ['photo-bikefit.jpg', 'Étude posturale dynamique sur vélo'],
                        ],
                    ],
                    [
                        'title' => 'Sur place',
                        'list' => [
                            'Entraînements applicables sur votre plateforme favorite, dont Nöliö',
                            'Analyse du cycle de pédalage et de la position aérodynamique',
                            'Capteur de pression de selle Velometrik et essai de selles haut de gamme',
                            'Simulation de soufflerie Bioracer Aero, en exclusivité en Wallonie',
                        ],
                        'photos' => [
                            ['photo-selle.jpg', 'Capteur de pression de selle Velometrik'],
                            ['photo-selles.webp', 'Essai de selles haut de gamme'],
                        ],
                    ],
                ],
                'close' => 'Quel que soit votre niveau ou votre discipline, l’objectif est de vous aider à atteindre votre plus haut niveau.',
            ],
            'entreprise' => [
                'title' => 'Coaching en entreprise',
                'kicker' => 'La santé de l’entreprise, c’est aussi celle des équipes',
                'image' => 'photo-entreprise.jpg',
                'paragraphs' => [
                    'Chaque personne étant unique, l’intervention d’un personal trainer prend tout son sens dans l’amélioration des facultés physiques et psychologiques des employés.',
                    'De plus en plus de personnes s’éloignent des activités sportives et subissent leur sédentarité : horaires, vie de famille, manque de stimulations. Les conséquences touchent les défenses de l’organisme, les capacités physiques et l’épanouissement.',
                    'Certaines activités amènent les équipes à sortir de leur zone de confort, à se dépasser, et à développer combativité et coopération. Les bénéfices se retrouvent dans le bien-être, et aussi dans la productivité.',
                ],
                'list_title' => 'Bénéfices pour l’employeur',
                'groups' => [
                    ['Changements positifs', [
                        'Réduction de l’absentéisme',
                        'Réduction des accidents de travail',
                        'Amélioration des relations au travail',
                        'Amélioration de la qualité du travail',
                        'Amélioration de l’engagement des salariés',
                        'Amélioration de l’attractivité de l’entreprise',
                    ]],
                    ['Bénéfices psycho-sociaux', [
                        'Amélioration du moral',
                        'Amélioration de la concentration',
                        'Impact positif sur la culture d’entreprise',
                        'Amélioration des rapports sociaux',
                        'Amélioration de la satisfaction au travail',
                        'Réduction du stress',
                    ]],
                    ['Bénéfices financiers', [
                        'Réduction des coûts de santé',
                        'Réduction des coûts liés à l’absentéisme',
                        'Retour sur investissement',
                    ]],
                ],
                'blocks' => [
                    ['Comment cela se passe', 'Séance d’information et/ou questionnaire : besoins, attentes, nature des activités, mise en place concrète. Puis définition du programme, lancement du projet et suivi des résultats, avec ajustements.'],
                ],
            ],
            'kinesitherapie' => [
                'title' => 'Kinésithérapie générale et sportive',
                'kicker' => 'Marion Van Genechten · Marcinelle',
                'image' => 'photo-kine.webp',
                'paragraphs' => [
                    'Sur base de votre prescription médicale, un suivi de qualité est mis en place afin de répondre à vos attentes en réadaptation physique et fonctionnelle.',
                    'Au fil des consultations, le thérapeute propose un traitement adapté à la pathologie générale ou sportive, à l’écoute, en respectant votre rythme de progression.',
                    'Un suivi pluridisciplinaire peut être indiqué (ostéopathe, posturologue, podologue, préparateur physique), ainsi qu’un travail en autonomie, au cabinet ou à domicile.',
                ],
                'list_title' => 'Spécialités',
                'list' => [
                    'Prise en charge par le mouvement : souplesse, renforcement musculaire, travail de la posture',
                    'Traitement par ondes de choc : méthode non invasive pour diminuer les douleurs et favoriser la guérison des tissus musculo-tendineux',
                ],
                'booking' => [
                    'title' => 'Prise de rendez-vous',
                    'name' => 'Marion Van Genechten',
                    'phone' => '+32 494 10 88 13',
                    'phone_href' => 'marion_tel',
                    'mail' => 'marionvege@hotmail.com',
                    'mail_href' => 'marion_mail',
                    'address' => 'Rue de la Bruyère 240, 6001 Marcinelle',
                    'note' => 'Déplacement à domicile possible (grand Charleroi)',
                ],
            ],
            'mentions' => [
                'title' => 'Mentions',
                'kicker' => 'Pro-Fit.be',
                'image' => 'logo.png',
                'paragraphs' => [
                    'Pro-Fit.be — Adrien Gain. TVA BE 0534.564.822.',
                    'Studio : rue de la Bruyère 240, 6001 Marcinelle (Charleroi).',
                    'Contact : gain.adrien@gmail.com · +32 474 48 82 73. Kinésithérapie : marionvege@hotmail.com · +32 494 10 88 13.',
                    'Ce site n’utilise qu’un cookie technique de session, le temps d’envoyer le formulaire de contact, et mémorise localement votre choix sur la bannière cookies. Les liens vers Google, Instagram, Facebook ou LinkedIn sont des sites externes.',
                ],
            ],
            'contact' => [
                'title' => 'Contact',
                'kicker' => 'Charleroi et à distance',
            ],
        ],
        'team' => [
            'title' => 'L’équipe',
            'people' => [
                [
                    'name' => 'Adrien Gain',
                    'role' => 'Plans d’entraînement et bike fitting',
                    'place' => 'Studio à Charleroi et coaching à distance (international)',
                    'photo' => 'portrait-a.jpg',
                    'mail' => 'adrien_mail',
                    'tel' => 'adrien_tel',
                    'tel_label' => '+32 474 48 82 73',
                    'formations_title' => 'Formations en coaching sportif et bike fitting',
                    'formations' => [
                        'Bachelier en éducation physique (Henallux)',
                        'Diplôme universitaire européen en préparation physique (Université de Lille 2)',
                        'AUEC Réathlétisation du sportif (Université de Lille 2)',
                        'Bike Fitting – Préférences motrices 1.0 (Volodalen, Suisse)',
                        'Bike fitting – triathlon and time trial specifics (Gebiomized ISCO)',
                        'Nutrition du sportif (UCLouvain)',
                        'Posturologie et posturo-thérapie (SFER)',
                        'EXOS – Performance Specialist',
                        'Ironman® – Triathlon Certified Coach',
                        'Personal Training (Haute École Léonard de Vinci)',
                        'Taping sportif (UCLouvain)',
                        'Functional Movement Screening – FMS Level 1',
                        'La Clinique du Coureur 1.0',
                    ],
                ],
                [
                    'name' => 'Marion Van Genechten',
                    'role' => 'Kinésithérapie générale et sportive',
                    'place' => 'Studio situé à Charleroi',
                    'photo' => 'portrait-b.jpg',
                    'mail' => 'marion_mail',
                    'tel' => 'marion_tel',
                    'tel_label' => '+32 494 10 88 13',
                    'formations_title' => 'Formations en kinésithérapie',
                    'formations' => [
                        'Master en kinésithérapie (Condorcet, Tournai)',
                        'Kinésithérapie du sport (Kineac, Charleroi)',
                        'Gym Pilates appliquée à la kinésithérapie (SSK-Formation, Villeneuve d’Ascq)',
                        'AUEC Réathlétisation du sportif (Université de Lille 2)',
                    ],
                ],
            ],
        ],
        'reviews' => [
            'title' => 'Avis vérifiés',
            'lead' => 'Avis Google de personnes venues au studio.',
            'cta' => 'Lire les avis Google',
            'items' => $reviews,
        ],
        'instagram' => [
            'title' => 'Instagram',
            'handle' => '@adriengain_profitbe',
            'bio' => 'Plans d’entraînement et étude posturale dynamique cyclisme. Nutrition du sportif.',
            'cta' => 'Suivre sur Instagram',
        ],
        'tarifs' => [
            'title' => 'Tarifs',
            'updated' => 'Mise à jour : 1er octobre 2026',
            'jumps' => [
                ['coaching', 'Coaching'],
                ['fitting', 'Bike fitting'],
                ['packs', 'Packs'],
                ['valise', 'Location valise'],
                ['plans', 'Plans préconçus'],
            ],
            'from' => 'À partir de',
            'trial' => '1 semaine d’essai gratuite et sans engagement pour tout coaching.',
            'columns' => ['Durée', 'Payé en une fois', 'En mensualités'],
            'note' => 'Mensualités : prélèvement automatique, avec engagement sur la durée choisie (sauf la formule d’1 mois). Le coaching comprend un plan personnalisé, l’analyse des séances, un contact par messagerie, l’ajustement du plan et l’accès gratuit à l’application Nöliö.',
            'offers' => [
                [
                    'name' => 'Coaching triathlon et cyclisme',
                    'rows' => [
                        ['period' => '1 mois', 'note' => 'sans engagement', 'once' => '90 €', 'once_note' => '', 'month' => '95 € / mois', 'best' => false],
                        ['period' => '3 mois', 'note' => '', 'once' => '80 € / mois', 'once_note' => '240 € au total', 'month' => '85 € / mois', 'best' => false],
                        ['period' => '6 mois', 'note' => '', 'once' => '70 € / mois', 'once_note' => '420 € au total', 'month' => '75 € / mois', 'best' => false],
                        ['period' => '12 mois', 'note' => 'le meilleur prix', 'once' => '60 € / mois', 'once_note' => '720 € au total', 'month' => '65 € / mois', 'best' => true],
                    ],
                ],
                [
                    'name' => 'Coaching running et trail',
                    'rows' => [
                        ['period' => '1 mois', 'note' => 'sans engagement', 'once' => '70 €', 'once_note' => '', 'month' => '75 € / mois', 'best' => false],
                        ['period' => '3 mois', 'note' => '', 'once' => '65 € / mois', 'once_note' => '195 € au total', 'month' => '70 € / mois', 'best' => false],
                        ['period' => '6 mois', 'note' => '', 'once' => '60 € / mois', 'once_note' => '360 € au total', 'month' => '65 € / mois', 'best' => false],
                        ['period' => '12 mois', 'note' => 'le meilleur prix', 'once' => '55 € / mois', 'once_note' => '660 € au total', 'month' => '60 € / mois', 'best' => true],
                    ],
                ],
            ],
            'fit' => [
                'title' => 'Bike fitting',
                'rows' => [
                    ['Étude posturale route, gravel ou VTT', 'Analyse vidéo, capteur de pression de selle, cales, pré-fit et post-fit', '200 €'],
                    ['Étude posturale triathlon avec Bioracer Aero', 'Simulation de soufflerie, gains en puissance et en temps', '260 €'],
                    ['Fitting avec contrôle à 3 mois', 'Séance de vérification après 3 mois', '230 €'],
                    ['Réglage de cales', '', '40 €'],
                ],
            ],
            'packs' => [
                'title' => 'Packs fitting + coaching',
                'lead' => 'Vous commencez par 1 mois de coaching sans engagement. Ensuite, vous vous engagez sur une période et le fitting est réalisé au cours du 2e mois, avec un avantage selon la durée choisie.',
                'columns' => ['Engagement après le 1er mois', 'Avantage sur le fitting'],
                'rows' => [
                    ['3 mois', '−20 %', false],
                    ['6 mois', '−50 %', false],
                    ['12 mois', 'Fitting offert', true],
                ],
                'note' => 'Le 1er mois est facturé au tarif d’1 mois de votre discipline, puis les mensualités suivent la grille ci-dessus. Pack Reprise (triathlon-cyclisme) : 1 mois de coaching puis fitting au 2e mois, 250 € au lieu de 290 €.',
            ],
            'perks' => [
                'title' => 'Avantages pour les coachés',
                'items' => [
                    '−10 % sur tous les autres services',
                    '−20 % sur le bike fitting dès 6 mois d’engagement',
                    'Pause possible en cas de blessure ou de maladie, avec certificat médical',
                ],
                'note' => 'Rétractation de 14 jours, engagement et pause : voir les conditions générales.',
            ],
            'case' => [
                'title' => 'Location valise vélo',
                'from' => '30 €',
                'rows' => [
                    ['Jour', '30 €'],
                    ['Week-end', '70 €'],
                    ['Semaine', '120 €'],
                    ['Caution', '300 €'],
                ],
                'text' => 'L’Aerocomfort 3.0 Triathlon transporte un vélo de triathlon ou de chrono en avion, sans démonter la selle, la tige de selle, les pédales ni la majorité des guidons. Kit de protection compris (pédalier, prolongateurs, selle, dérailleur).',
            ],
            'ready' => [
                'title' => 'Plans préconçus',
                'lead' => 'Chaque plan prévoit un essai gratuit (première semaine offerte), l’application mobile et web, le suivi de la progression et les échanges avec l’entraîneur.',
                'weeks' => 'semaines',
            ],
        ],
        'blog' => [
            'title' => 'Le blog des sportifs',
            'lead' => 'Études posturales, entraînement et récits d’athlètes.',
            'read' => 'Lire',
            'back' => 'Retour au blog',
        ],
        'articles' => [
            [
                'slug' => 'etude-posturale-velo',
                'date' => '2023-09-06',
                'category' => 'Étude posturale',
                'title' => 'L’art et la science de l’étude posturale sur vélo',
                'excerpt' => 'Un bon ajustement aligne le vélo sur votre biomécanique : confort, efficacité, performance.',
                'image' => 'photo-selle.jpg',
                'body' => [
                    'Que vous soyez un cycliste occasionnel ou un cycliste sérieux, l’un des aspects les plus cruciaux de votre expérience à vélo est l’ajustement. Un bon ajustement personnalise le vélo pour la biomécanique de votre corps.',
                    'Pourquoi c’est important. L’ajustement ne se limite pas à la hauteur de selle ou à la position du guidon. Un vélo bien réglé limite l’inconfort, les douleurs articulaires et les blessures.',
                    'Confort : un vélo mal ajusté gâche la sortie, ou vous éloigne du vélo. Efficacité : un bon réglage optimise le transfert de puissance, coup de pédale après coup de pédale. Prévention : moins de contrainte inutile sur les articulations et les muscles. Performance : aérodynamisme, puissance, et de meilleures sorties longues ou en course.',
                    'Le processus. Un bike fitter qualifié commence par vos objectifs, votre expérience et votre santé, puis votre style, votre fréquence et le terrain. Des mesures (jambes, torse, bras) fondent les réglages. Le type et la taille de vélo peuvent être recommandés.',
                    'Hauteur et recul de selle pour une extension de jambe utile, sans surcharger le genou. Guidon réglé pour une portée et une position des mains confortables. Cales alignées si vous roulez en pédales automatiques. Évaluation dynamique : la position est observée en mouvement, puis affinée.',
                    'Ce n’est pas un réglage unique. Avec l’expérience, la forme, ou une douleur, l’ajustement se revoit. Un vélo bien réglé permet de rouler plus longtemps, plus vite, et avec plus de plaisir.',
                ],
            ],
            [
                'slug' => 'entrainement-polarise-80-20',
                'date' => '2025-01-28',
                'category' => 'Plan d’entraînement',
                'title' => 'L’entraînement polarisé : 80/20',
                'excerpt' => '80 % à basse intensité, 20 % à haute intensité : performer sans s’épuiser.',
                'image' => 'photo-polarise.jpg',
                'body' => [
                    'Le principe 80/20 vise à optimiser les performances tout en limitant le surentraînement et la fatigue. L’intensité se répartit en deux zones : basse et haute.',
                    '80 % de l’entraînement se fait à intensité faible à modérée, pour l’endurance et l’aérobie : course, vélo ou natation à un rythme où l’on peut parler. 20 % se fait à intensité élevée : intervalles, sprints, efforts qui poussent le corps.',
                    'L’objectif est de progresser sans fatigue excessive ni blessure. Le corps récupère mieux et s’adapte. Pour l’endurance, cette base aérobie est essentielle sur la durée.',
                    'La méthode invite à écouter le corps. Les jours bas, mieux vaut rester à faible intensité. Sur 10 heures par semaine, 8 heures restent faciles et 2 heures sont intenses.',
                    'Équilibrer faible et haute intensité maximise les bénéfices et garde une pratique durable. Mise à jour : 28 janvier 2025.',
                ],
            ],
            [
                'slug' => 'entrainement-a-distance',
                'date' => '2024-02-14',
                'category' => 'Plan d’entraînement',
                'title' => 'Les avantages de l’entraînement à distance pour les sports d’endurance',
                'excerpt' => 'Flexibilité, entraîneur certifié, plan personnalisé : s’entraîner où que l’on soit.',
                'image' => 'photo-distance.png',
                'body' => [
                    'Le sport d’endurance est exigeant. Le triathlon en est un exemple : concilier natation, cyclisme et course à pied demande une planification rigoureuse. L’entraînement à distance est une des façons d’organiser ce travail.',
                    'Flexibilité. Les séances se placent dans un emploi du temps chargé, sans devoir coordonner les horaires de piscine, de piste et de route.',
                    'Un entraîneur certifié. Les plateformes en ligne et les applications de suivi rendent ce coaching accessible, quel que soit le lieu de résidence.',
                    'Personnalisation. Le programme suit les objectifs, le niveau et les contraintes de chacun.',
                    'Temps et argent. Les déplacements et les adhésions à des clubs sortent de l’équation.',
                    'Motivation. Le suivi, une communauté de pairs et un coach à qui rendre compte aident à rester régulier.',
                    'Conseils pratiques. Gardez un contact régulier et décrivez comment les séances se sont vraiment passées. Apprenez les outils que vous utilisez déjà : montre GPS, capteurs de fréquence cardiaque ou de puissance, applications de suivi. Fixez des objectifs clairs avec votre coach. Restez prêt à ajuster le plan en cas de blessure, de maladie ou de changement de calendrier.',
                    'L’entraînement à distance permet de s’entraîner efficacement, où que l’on soit, pour une compétition ou simplement pour le plaisir. Mise à jour : 14 février 2024.',
                ],
            ],
            [
                'slug' => 'meditation-et-sport',
                'date' => '2023-09-11',
                'category' => 'Préparation physique',
                'title' => 'Les bienfaits de la méditation pour la santé mentale et le bien-être physique',
                'excerpt' => 'Moins de stress, plus de concentration, un meilleur sommeil, un système immunitaire plus solide.',
                'image' => 'meditation.jpg',
                'body' => [
                    'La méditation est une pratique ancienne qui gagne en popularité.',
                    'En l’intégrant au quotidien, on peut réduire le stress, améliorer la concentration, renforcer la résilience émotionnelle, améliorer le sommeil et soutenir le système immunitaire.',
                ],
            ],
            [
                'slug' => 'kona-marjolaine',
                'date' => '2026-02-15',
                'category' => 'Compte rendu d’athlète',
                'title' => 'Championnats du monde Ironman à Hawaï pour Marjolaine',
                'excerpt' => 'Deux semaines après Kona : une qualification inattendue, et une journée à honorer.',
                'image' => 'photo-marjo.jpg',
                'body' => [
                    'Deux semaines se sont écoulées depuis le Championnat du Monde Ironman à Kona. Assez pour que l’adrénaline retombe. Le corps a récupéré, le quotidien a repris. Et c’est dans cette normalité que je mesure vraiment ce que j’ai vécu.',
                    'Je ne m’attendais pas à être qualifiée pour Kona. Trois mois pour préparer un championnat du monde, entre le travail, la logistique du voyage et un apprentissage express du vélo contre-la-montre. C’était intense, parfois trop.',
                    'Puis on arrive sur cette île. Le travail est fait, on profite de chaque jour, de cette fête autour du sport. Le jour J, une excitation sereine. Impossible de s’aligner sans un peu de doute, mais avec le sentiment d’être prête.',
                    'Une natation longue, houleuse, mais belle. L’eau était claire, pleine de poissons. J’ai nagé sans pression, juste avec la joie d’être là.',
                    'Un vélo plus difficile que prévu. La chaleur, le vent, la position aéro encore nouvelle. Des douleurs, quelques doutes, puis j’ai accepté de ralentir. J’ai pensé au marathon, à la suite, à l’essentiel.',
                    'Une course à pied d’abord douloureuse. Puis, comme souvent, tout s’est débloqué. Le corps a trouvé son rythme, le mental s’est apaisé. Glaçons, bob, sourires. J’ai avancé le cœur léger. Quand j’ai franchi la ligne, j’étais simplement bien. Présente. Reconnaissante.',
                    'Deuxième Ironman. Mais sûrement pas le dernier. — Marjolaine',
                ],
            ],
        ],
        'contact' => [
            'title' => 'Écrire au studio',
            'lead' => 'Une question sur un plan, un bike fitting ou la kinésithérapie. Nous répondons directement.',
            'name' => 'Nom',
            'email' => 'E-mail',
            'phone' => 'Téléphone',
            'message' => 'Message',
            'subject' => 'Sujet',
            'subjects' => [
                'bikefit' => 'Bike fitting',
                'plan' => 'Plan d’entraînement',
                'kine' => 'Kinésithérapie',
                'autre' => 'Autre demande',
            ],
            'reply' => 'Vous préférez être recontacté',
            'reply_email' => 'Par e-mail',
            'reply_phone' => 'Par téléphone',
            'send' => 'Envoyer',
            'success' => 'Message bien reçu. Nous vous répondons rapidement.',
            'error' => 'Merci de vérifier le nom, l’e-mail et le message.',
            'address' => 'Rue de la Bruyère 240, 6001 Marcinelle',
        ],
        'footer' => 'TVA BE 0534.564.822',
        'cookies' => 'Aucun traceur n’est chargé tant que vous n’avez pas accepté. Le choix est mémorisé 6 mois sur cet appareil.',
        'cookies_ok' => 'Accepter',
        'cookies_no' => 'Refuser',
        'cookies_manage' => 'Gérer les cookies',
        'map' => 'Voir sur Google Maps',
        'links' => $links,
        'plans' => $plans,
    ],
    'en' => [
        'meta' => [
            'home_title' => 'Training plans, physiotherapy and bike fitting in Charleroi',
            'description' => 'Pro-Fit.be — training plans, sports physiotherapy and bike fitting, in Charleroi and remotely.',
        ],
        'nav' => [
            ['home', 'Home'],
            ['velo', 'Training plan'],
            ['kinesitherapie', 'Physiotherapy'],
            ['blog', 'Blog'],
            ['tarifs', 'Prices'],
            ['contact', 'Contact'],
        ],
        'book' => 'Book a bike fit',
        'discover' => 'Discover',
        'hero' => [
            'kicker' => 'Charleroi · Marcinelle · remote',
            'title' => 'Bike fitting, training plans and physiotherapy in Charleroi.',
            'lead' => 'A studio at 240 rue de la Bruyère in Marcinelle. Adrien Gain runs bike fits and coaches triathlon, cycling, running and trail. Marion Van Genechten sees patients for general and sports physiotherapy.',
        ],
        'services' => [
            ['velo', 'Training plan', 'Dynamic bike fit', 'Comfort, power and aerodynamics.', 'photo-bikefit.jpg'],
            ['kinesitherapie', 'Physiotherapy', 'General and sports', 'Rehab at the studio or at home.', 'photo-kine.webp'],
        ],
        'pages' => [
            'coaching' => [
                'title' => 'Sports coaching – Physical preparation',
                'kicker' => 'Studio in Marcinelle and international follow-up',
                'image' => 'photo-coaching.jpg',
                'photos' => [
                    ['photo-coaching.jpg', 'Physical preparation'],
                    ['photo-coaching-trx.jpg', 'Personal training'],
                    ['photo-coaching-plank.jpg', 'Strength work'],
                ],
                'paragraphs' => [
                    'Once your goal is clear (fat loss, muscle gain, mobility, strength…) and a full assessment is done from your own data (heart rate, fat mass, lean mass…), my role as a qualified coach is to build a personal programme.',
                    'The coaching studio in Charleroi (Marcinelle) has the equipment you need: a strength rack, kettlebells, Swiss ball, TRX, BOSU and rings.',
                    'My aim is to help you reach your goal as soon as it is realistic — and to leave you able to do it again on your own.',
                ],
                'list_title' => 'Three advantages of personal training',
                'list' => [
                    'Follow-up by a qualified coach',
                    'Weight tracking and adapted nutrition advice',
                    'Motivation and support whenever you need it',
                ],
                'close' => 'Stop setting limits. Book a first session.',
            ],
            'velo' => [
                'title' => 'Training plans and dynamic bike fitting',
                'kicker' => 'Cycling, running, trail, triathlon',
                'image' => 'photo-bikefit.jpg',
                'paragraphs' => [
                    'Looking for a cycling, running, trail or triathlon plan, with regular contact with a qualified coach?',
                    'Want a better position on the bike: more comfort, more performance, more aerodynamics?',
                    'Want field testing with a lactate meter, then training zones you can actually use?',
                    'Does your level call for extra work outside the sessions of your sport, team or individual?',
                ],
                'sections' => [
                    [
                        'title' => 'Training plan',
                        'paragraphs' => [
                            'Plans are available for triathlon, cycling, running and trail. A first meeting sets the goals. Effort tests on a home trainer, with the Lactate Scout 4 sensor, track progress and define training zones.',
                        ],
                        'photos' => [
                            ['photo-zwift.jpg', 'Training on the platform you already use'],
                            ['photo-nolio.png', 'Nöliö, follow-up for the training plan'],
                        ],
                    ],
                    [
                        'title' => 'Dynamic bike fit',
                        'paragraphs' => [
                            'The fit follows your motor preferences, your discipline and what you want (aero, power, comfort). After posture and mobility tests and a pedal-stroke analysis, adjustments are made on your bike — road, triathlon, MTB — including cleats.',
                            'The Velometrik saddle-pressure sensor is used to place you correctly. A set of high-end saddles is available during the fit. For more competitive athletes, and exclusive in Wallonia, the Bioracer Aero wind-tunnel simulation estimates power and speed gains in real time.',
                            'You leave with a before / after report. A strength and stretching programme can be added.',
                        ],
                        'photos' => [
                            ['photo-analyse.jpg', 'Video analysis of the position'],
                            ['photo-aero-ecran.jpg', 'Power and speed gains, in real time'],
                            ['photo-bikefit.jpg', 'Dynamic bike fitting'],
                        ],
                    ],
                    [
                        'title' => 'In the studio',
                        'list' => [
                            'Sessions you can load on your usual platform, including Nöliö',
                            'Pedal-stroke and aerodynamic position analysis',
                            'Velometrik saddle-pressure sensor and a range of high-end saddles',
                            'Bioracer Aero wind-tunnel simulation, exclusive in Wallonia',
                        ],
                        'photos' => [
                            ['photo-selle.jpg', 'Velometrik saddle pressure sensor'],
                            ['photo-selles.webp', 'Try a range of high-end saddles'],
                        ],
                    ],
                ],
                'close' => 'Whatever your level or your sport, the aim is to help you reach your highest level.',
            ],
            'entreprise' => [
                'title' => 'Corporate coaching',
                'kicker' => 'A healthier company starts with healthier people',
                'image' => 'photo-entreprise.jpg',
                'paragraphs' => [
                    'Because every person is different, a personal trainer can improve both the physical and psychological capacities of employees.',
                    'Many people drop sport and live with the consequences of sitting still: schedules, family life, lack of a spark. That shows up in immunity, physical capacity and how people feel at work.',
                    'The right activities take teams out of their usual comfort zone, and build both drive and cooperation. The gain is wellbeing, and also productivity.',
                ],
                'list_title' => 'What the employer gets',
                'groups' => [
                    ['Positive changes', [
                        'Less absenteeism',
                        'Fewer workplace accidents',
                        'Better working relationships',
                        'Better quality of work',
                        'Stronger employee engagement',
                        'A more attractive company',
                    ]],
                    ['Psychosocial benefits', [
                        'Better morale',
                        'Better concentration',
                        'A positive effect on company culture',
                        'Better social relationships',
                        'Higher job satisfaction',
                        'Less stress',
                    ]],
                    ['Financial benefits', [
                        'Lower health costs',
                        'Lower costs linked to absenteeism',
                        'A return on the investment',
                    ]],
                ],
                'blocks' => [
                    ['How it works', 'An information session and/or a questionnaire: needs, expectations, which activities, and how they fit the company. Then the programme is defined, launched and adjusted from the results.'],
                ],
            ],
            'kinesitherapie' => [
                'title' => 'General and sports physiotherapy',
                'kicker' => 'Marion Van Genechten · Marcinelle',
                'image' => 'photo-kine.webp',
                'paragraphs' => [
                    'With your medical prescription, care is set up around what you need in physical and functional rehab.',
                    'Session after session, treatment matches a general or sports condition, at your pace.',
                    'A multidisciplinary path can be suggested (osteopath, posturologist, podiatrist, strength coach), plus work you do on your own at the studio or at home.',
                ],
                'list_title' => 'Specialties',
                'list' => [
                    'Care through movement: flexibility, strength and posture',
                    'Shockwave therapy: a non-invasive way to reduce pain and help muscle and tendon tissue recover',
                ],
                'booking' => [
                    'title' => 'Book an appointment',
                    'name' => 'Marion Van Genechten',
                    'phone' => '+32 494 10 88 13',
                    'phone_href' => 'marion_tel',
                    'mail' => 'marionvege@hotmail.com',
                    'mail_href' => 'marion_mail',
                    'address' => 'Rue de la Bruyère 240, 6001 Marcinelle',
                    'note' => 'Home visits possible across greater Charleroi',
                ],
            ],
            'mentions' => [
                'title' => 'Legal',
                'kicker' => 'Pro-Fit.be',
                'image' => 'logo.png',
                'paragraphs' => [
                    'Pro-Fit.be — Adrien Gain. VAT BE 0534.564.822.',
                    'Studio: rue de la Bruyère 240, 6001 Marcinelle (Charleroi), Belgium.',
                    'Contact: gain.adrien@gmail.com · +32 474 48 82 73. Physiotherapy: marionvege@hotmail.com · +32 494 10 88 13.',
                    'This site only uses a technical session cookie while the contact form is sent, and stores your cookie choice locally in the browser. Google, Instagram, Facebook and LinkedIn links are external sites.',
                ],
            ],
            'contact' => [
                'title' => 'Contact',
                'kicker' => 'Charleroi and remote',
            ],
        ],
        'team' => [
            'title' => 'The team',
            'people' => [
                [
                    'name' => 'Adrien Gain',
                    'role' => 'Training plans and bike fitting',
                    'place' => 'Studio in Charleroi and remote coaching (international)',
                    'photo' => 'portrait-a.jpg',
                    'mail' => 'adrien_mail',
                    'tel' => 'adrien_tel',
                    'tel_label' => '+32 474 48 82 73',
                    'formations_title' => 'Coaching and bike-fitting training',
                    'formations' => [
                        'Bachelor in physical education (Henallux)',
                        'European university diploma in physical preparation (University of Lille 2)',
                        'AUEC athlete reconditioning (University of Lille 2)',
                        'Bike Fitting – Motor preferences 1.0 (Volodalen, Switzerland)',
                        'Bike fitting – triathlon and time trial specifics (Gebiomized ISCO)',
                        'Sports nutrition (UCLouvain)',
                        'Posturology and posturo-therapy (SFER)',
                        'EXOS – Performance Specialist',
                        'Ironman® – Triathlon Certified Coach',
                        'Personal Training (Haute École Léonard de Vinci)',
                        'Sports taping (UCLouvain)',
                        'Functional Movement Screening – FMS Level 1',
                        'La Clinique du Coureur 1.0',
                    ],
                ],
                [
                    'name' => 'Marion Van Genechten',
                    'role' => 'General and sports physiotherapy',
                    'place' => 'Studio in Charleroi',
                    'photo' => 'portrait-b.jpg',
                    'mail' => 'marion_mail',
                    'tel' => 'marion_tel',
                    'tel_label' => '+32 494 10 88 13',
                    'formations_title' => 'Physiotherapy training',
                    'formations' => [
                        'Master in physiotherapy (Condorcet, Tournai)',
                        'Sports physiotherapy (Kineac, Charleroi)',
                        'Pilates applied to physiotherapy (SSK-Formation, Villeneuve d’Ascq)',
                        'AUEC athlete reconditioning (University of Lille 2)',
                    ],
                ],
            ],
        ],
        'reviews' => [
            'title' => 'Verified reviews',
            'lead' => 'Google reviews from people who came to the studio.',
            'cta' => 'Read the Google reviews',
            'items' => $reviews,
        ],
        'instagram' => [
            'title' => 'Instagram',
            'handle' => '@adriengain_profitbe',
            'bio' => 'Training plans and dynamic cycling bike fits. Sports nutrition.',
            'cta' => 'Follow on Instagram',
        ],
        'tarifs' => [
            'title' => 'Prices',
            'jumps' => [
                ['coaching', 'Coaching'],
                ['fitting', 'Bike fitting'],
                ['packs', 'Packs'],
                ['valise', 'Travel case'],
                ['plans', 'Ready-made plans'],
            ],
            'updated' => 'Updated 1 October 2026',
            'from' => 'From',
            'trial' => 'One free trial week, with no commitment, for every coaching plan.',
            'columns' => ['Length', 'Paid in one go', 'Monthly'],
            'note' => 'Monthly payments are taken automatically, with a commitment for the chosen length (except the 1-month plan). Coaching includes a personal plan, session analysis, contact by message, plan adjustments and free access to the Nöliö app.',
            'offers' => [
                [
                    'name' => 'Triathlon and cycling coaching',
                    'rows' => [
                        ['period' => '1 month', 'note' => 'no commitment', 'once' => '€90', 'once_note' => '', 'month' => '€95 / month', 'best' => false],
                        ['period' => '3 months', 'note' => '', 'once' => '€80 / month', 'once_note' => '€240 in total', 'month' => '€85 / month', 'best' => false],
                        ['period' => '6 months', 'note' => '', 'once' => '€70 / month', 'once_note' => '€420 in total', 'month' => '€75 / month', 'best' => false],
                        ['period' => '12 months', 'note' => 'best price', 'once' => '€60 / month', 'once_note' => '€720 in total', 'month' => '€65 / month', 'best' => true],
                    ],
                ],
                [
                    'name' => 'Running and trail coaching',
                    'rows' => [
                        ['period' => '1 month', 'note' => 'no commitment', 'once' => '€70', 'once_note' => '', 'month' => '€75 / month', 'best' => false],
                        ['period' => '3 months', 'note' => '', 'once' => '€65 / month', 'once_note' => '€195 in total', 'month' => '€70 / month', 'best' => false],
                        ['period' => '6 months', 'note' => '', 'once' => '€60 / month', 'once_note' => '€360 in total', 'month' => '€65 / month', 'best' => false],
                        ['period' => '12 months', 'note' => 'best price', 'once' => '€55 / month', 'once_note' => '€660 in total', 'month' => '€60 / month', 'best' => true],
                    ],
                ],
            ],
            'fit' => [
                'title' => 'Bike fitting',
                'rows' => [
                    ['Road, gravel or MTB fit', 'Video analysis, saddle-pressure sensor, cleats, pre-fit and post-fit', '€200'],
                    ['Triathlon fit with Bioracer Aero', 'Wind-tunnel simulation, gains in power and time', '€260'],
                    ['Fit with a 3-month check', 'A review session after 3 months', '€230'],
                    ['Cleat adjustment', '', '€40'],
                ],
            ],
            'packs' => [
                'title' => 'Fit and coaching packs',
                'lead' => 'You start with 1 month of coaching and no commitment. You then commit for a period, and the fit takes place during the 2nd month, with a discount that depends on the length.',
                'columns' => ['Commitment after month 1', 'Fit discount'],
                'rows' => [
                    ['3 months', '−20%', false],
                    ['6 months', '−50%', false],
                    ['12 months', 'Fit included', true],
                ],
                'note' => 'Month 1 is charged at the 1-month rate for your sport, then the monthly price follows the grid above. Return pack (triathlon and cycling): 1 month of coaching, then a fit in month 2, €250 instead of €290.',
            ],
            'perks' => [
                'title' => 'Advantages for coached athletes',
                'items' => [
                    '−10% on every other service',
                    '−20% on a bike fit from 6 months of commitment',
                    'A pause is possible for injury or illness, with a medical certificate',
                ],
                'note' => 'The 14-day withdrawal, the commitment and the pause are set out in the terms.',
            ],
            'case' => [
                'title' => 'Bike travel-case hire',
                'from' => '€30',
                'rows' => [
                    ['Day', '€30'],
                    ['Weekend', '€70'],
                    ['Week', '€120'],
                    ['Deposit', '€300'],
                ],
                'text' => 'The Aerocomfort 3.0 Triathlon flies a triathlon or time-trial bike without removing the saddle, seatpost, pedals or most handlebars. Protection kit included (crank, extensions, saddle, derailleur).',
            ],
            'ready' => [
                'title' => 'Ready-made plans',
                'lead' => 'Each plan includes a free trial (first week on the coach), the mobile and web app, progress tracking and messages with the coach.',
                'weeks' => 'weeks',
            ],
        ],
        'blog' => [
            'title' => 'The athletes’ blog',
            'lead' => 'Bike fits, training and athlete stories.',
            'read' => 'Read',
            'back' => 'Back to the blog',
        ],
        'articles' => [
            [
                'slug' => 'etude-posturale-velo',
                'date' => '2023-09-06',
                'category' => 'Bike fit',
                'title' => 'The art and science of a dynamic bike fit',
                'excerpt' => 'A proper fit matches the bike to your body: comfort, efficiency, performance.',
                'image' => 'photo-selle.jpg',
                'body' => [
                    'Whether you ride occasionally or seriously, fit is one of the most important parts of cycling. A good fit tunes the bike to your biomechanics.',
                    'Why it matters. Fit is more than saddle height or handlebar position. A well-set bike reduces discomfort, joint pain and injury.',
                    'Comfort: a poor fit spoils the ride, or stops you riding. Efficiency: a good setup transfers power, pedal stroke after pedal stroke. Injury prevention: less useless load on joints and muscles. Performance: aerodynamics, power, and better long rides or races.',
                    'The process. A qualified fitter starts with your goals, experience and health, then your style, frequency and terrain. Body measurements (legs, torso, arms) drive the adjustments. Bike type and size can be recommended.',
                    'Saddle height and setback for a useful leg extension, without overloading the knee. Handlebar reach and hand position that spare the back, shoulders and arms. Cleats aligned if you ride clipless. A dynamic check: position is watched while you pedal, then refined.',
                    'It is not a one-off. Experience, fitness, or pain are reasons to revisit the fit. A well-set bike lets you ride longer, faster, and with more pleasure.',
                ],
            ],
            [
                'slug' => 'entrainement-polarise-80-20',
                'date' => '2025-01-28',
                'category' => 'Training plan',
                'title' => 'Polarised training: 80/20',
                'excerpt' => '80% easy, 20% hard: get faster without burning out.',
                'image' => 'photo-polarise.jpg',
                'body' => [
                    'The 80/20 principle aims to raise performance while limiting overtraining and fatigue. Intensity sits in two zones: low and high.',
                    '80% of training is easy to moderate, building endurance and aerobic capacity: running, cycling or swimming at a conversational pace. 20% is hard: intervals, sprints, efforts that push the body.',
                    'The goal is progress without excess fatigue or injury. The body recovers and adapts. For endurance athletes, that aerobic base is what lasts.',
                    'The method asks you to listen. On low days, stay easy. In a 10-hour week, 8 hours stay easy and 2 hours are intense.',
                    'Balancing easy and hard work keeps the gains and the habit. Updated 28 January 2025.',
                ],
            ],
            [
                'slug' => 'entrainement-a-distance',
                'date' => '2024-02-14',
                'category' => 'Training plan',
                'title' => 'Remote training for endurance sports',
                'excerpt' => 'Flexibility, a certified coach, a plan built around you — wherever you live.',
                'image' => 'photo-distance.png',
                'body' => [
                    'Endurance sport is demanding. Triathlon is a clear example: swimming, cycling and running together take careful planning and steady discipline. Remote coaching is one way athletes now organise that work.',
                    'Flexibility. Sessions fit a busy diary, without coordinating pool, track and road times.',
                    'A certified coach. Online platforms and tracking apps make that coaching available wherever you live.',
                    'A personal plan. The programme follows your goals, your fitness and your constraints.',
                    'Time and money. Travel and club memberships drop out of the equation.',
                    'Motivation. Tracking, a peer community and a coach to report to help keep the work consistent.',
                    'Practical points. Stay in regular contact and report how sessions actually went. Learn the tools you already use: GPS watch, heart-rate or power sensors, training apps. Set clear goals with your coach. Stay ready to adjust for injury, illness or a change of calendar.',
                    'Remote coaching is a way to train properly from wherever you are, for a race or simply for the pleasure of it. Updated 14 February 2024.',
                ],
            ],
            [
                'slug' => 'meditation-et-sport',
                'date' => '2023-09-11',
                'category' => 'Physical preparation',
                'title' => 'How meditation supports mental health and physical wellbeing',
                'excerpt' => 'Less stress, sharper focus, better sleep, a stronger immune system.',
                'image' => 'meditation.jpg',
                'body' => [
                    'Meditation is an old practice that is finding a new audience.',
                    'Brought into daily life, it can reduce stress, improve concentration, strengthen emotional resilience, improve sleep and support the immune system.',
                ],
            ],
            [
                'slug' => 'kona-marjolaine',
                'date' => '2026-02-15',
                'category' => 'Athlete report',
                'title' => 'Ironman World Championship in Hawaii for Marjolaine',
                'excerpt' => 'Two weeks after Kona: an unexpected qualification, and a day worth honouring.',
                'image' => 'photo-marjo.jpg',
                'body' => [
                    'Two weeks have passed since the Ironman World Championship in Kona. Long enough for the adrenaline to drop. The body has recovered, ordinary life is back. In that ordinary quiet, I can finally measure what I lived.',
                    'I did not expect to qualify for Kona. Three months to prepare a world championship, between work, travel logistics and a crash course on the time-trial bike. It was intense. Sometimes too much.',
                    'Then you land on the island. The work is done. You take each day, and the festival around the sport. On race morning, a calm excitement. You cannot start a day like that without some doubt — and still feel ready.',
                    'A long, choppy, beautiful swim. The water was clear, full of fish. I swam without pressure, just glad to be there.',
                    'The bike was harder than expected. Heat, wind, an aero position that was still new. Pain, a few doubts, then I accepted slowing down. I thought about the marathon, about what came next, about what mattered.',
                    'The run hurt at first. Then, as it often does, it opened up. The body found a rhythm, the mind settled. Ice, a cap, smiles. I moved forward lightly. Crossing the line, I simply felt well. Present. Grateful.',
                    'Second Ironman. Certainly not the last. — Marjolaine',
                ],
            ],
        ],
        'contact' => [
            'title' => 'Write to the studio',
            'lead' => 'A question about a plan, a bike fit or physiotherapy. We reply directly.',
            'name' => 'Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'message' => 'Message',
            'subject' => 'Subject',
            'subjects' => [
                'bikefit' => 'Bike fitting',
                'plan' => 'Training plan',
                'kine' => 'Physiotherapy',
                'autre' => 'Something else',
            ],
            'reply' => 'How should we reply',
            'reply_email' => 'By email',
            'reply_phone' => 'By phone',
            'send' => 'Send',
            'success' => 'Message received. We will reply shortly.',
            'error' => 'Please check the name, email and message.',
            'address' => 'Rue de la Bruyère 240, 6001 Marcinelle',
        ],
        'footer' => 'VAT BE 0534.564.822',
        'cookies' => 'No tracker is loaded until you accept. The choice is stored for 6 months on this device.',
        'cookies_ok' => 'Accept',
        'cookies_no' => 'Refuse',
        'cookies_manage' => 'Manage cookies',
        'map' => 'Open in Google Maps',
        'links' => $links,
        'plans' => $plans,
    ],
];
